# kubectl apply -f andre-hermoza-12-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: andre-hermoza-12-secret
  namespace: andre-hermoza-12-namespace
type: Opaque
data:
  PORT: ODA4Ng==
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLWxhdGUtZmlyZWZseS1hNGJrNjI0OC51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9pYXM/cmVxdWlyZSZjaGFubmVsQmluZGluZz1yZXF1aXJlJnNzbG1vZGU9cmVxdWlyZQ==  # en Base64
  DATABASE_USERNAME: bmVvbmRiX293bmVy   # en Base64
  DATABASE_PASSWORD: bnBnX2Yya0xWeng0bEZ3bw==   # en Base64
  RAPIDAPI_APIKEY: MGM0NDc3NjE1Y21zaDAzY2VhOWU2ODA4NzA1OHAxOWUzNTBqc243ZWYwZTRjODg3NDI=   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode